#:schema node_modules/wrangler/config-schema.json
name = "animeguri"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "animeguri-db"
database_id = "4aa02edd-9bf2-4e18-b3f5-62561061aa2f"
